# name: my_app
# description: "A new Flutter project."
# publish_to: 'none'

# version: 1.0.0+1

# environment:
#   sdk: ">=3.0.0 <4.0.0"

# dependencies:
#   flutter:
#     sdk: flutter
#   http: ^0.13.5
#   provider: ^6.0.5
#   shared_preferences: ^2.2.2
#   cupertino_icons: ^1.0.8
#   url_launcher: ^6.1.7
#   file_picker: ^5.4.6
#   local_auth: 2.1.6
#   path_provider: ^2.0.15   
#   flutter_pdfview: ^1.2.3 
#   flutter_plugin_android_lifecycle: ^2.0.9
 
# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^5.0.0
#   flutter_launcher_icons: ^0.13.1

# flutter:
#   uses-material-design: true

#   assets:
#     - images/admlogo.png
#     - assets/images/appbar_bg.png
#     # - images/user_profile.png
#     - images/pdf.png
#     - images/jpg.png
#     - assets/images/fingerprint.png
#     - assets/images/logo.png


# flutter_icons:
#   android: true
#   ios: true
#   image_path: "images/ic_launcher.png"
#   adaptive_icon_foreground: "images/ic_launcher.png"
#   adaptive_icon_background: "#ffffff"


name: my_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.7
  file_picker: ^6.1.1
  local_auth: 2.1.6
  path_provider: ^2.0.15
  flutter_pdfview: ^1.2.3
  flutter_plugin_android_lifecycle: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - images/admlogo.png
    - assets/images/appbar_bg.png
    # - images/user_profile.png
    - images/pdf.png
    - images/jpg.png
    - assets/images/fingerprint.png
    - assets/images/logo.png
    - assets/fonts/  # Added for font support

  fonts:  # Added fonts section
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-Italic.ttf
          style: italic

flutter_icons:
  android: true
  ios: true
  image_path: "images/ic_launcher.png"
  adaptive_icon_foreground: "images/ic_launcher.png"
  adaptive_icon_background: "#ffffff"